- mkdocs.yml
Inclusion of Water quality section
> Water quality update on Index

- mkdocs.yml
Reverts Fiware/dataModels#2
mkdocs.yml is wrong
> Revert "Water quality update on Index"

- WasteManagement/WasteContainer/doc/spec.md
Hi team,
With this PR we are proposing a new attribute (weight) for WasteContaniner entity.
Thanks!
Cayetano Benavent, Geographica
> New attribute proposed for WasteContainer: weight

- Parking/OffStreetParking/doc/spec.md
- Parking/OnStreetParking/doc/spec.md
- Parking/ParkingGroup/doc/spec.md
- Fixes https://github.com/Fiware/dataModels/issues/16
> Substituting maximumAParkingDuration by maximumParkingDuration

- Parking/ParkingSpot/doc/spec.md
- WasteManagement/WasteContainer/doc/spec.md
- Fixes https://github.com/Fiware/dataModels/issues/18
As you will see my editor has automatically fixed some blank spaces issues too... 8-)
> Removing references to "develop" branches

- Parking/OffStreetParking/doc/spec.md
- Parking/OffStreetParking/schema.json
New fields priceRatePerMinute,  priceCurrency, measuresPeriod and measuresPeriodUnit
> Introduction of new fields

- Transportation/doc/introduction.md
Fix broken links in the vehicle documentation
> Fix broken links in the vehicle documentation

- Environment/AirQualityObserved/harvest/barcelona_airquality_harvest.py
- Environment/AirQualityObserved/harvest/madrid_air_quality.py
- Environment/AirQualityObserved/harvest/madrid_air_quality_harvest.py
- Environment/AirQualityObserved/harvest/santander_federation.py
- PointOfInterest/WeatherStation/stations.py
- PointOfInterest/import_pois_tourspain.py
- Weather/WeatherForecast/harvest/aemet.py
- Weather/WeatherForecast/harvest/ipma.py
- Weather/WeatherForecast/harvest/portugal_weather_forecast_harvest.py
- Weather/WeatherObserved/harvest/spain_weather_observed_harvest.py
- Weather/WeatherObserved/harvest/weather_observed.py
- Weather/aemet.py
Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3. There would _probably_ be more work required to complete the port to Python 3 but this is a minimal, safe first step.
Run: `futurize --stage1 -w **/*.py`  # done in zsh for ** globbing
See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes
$ `pip install future`
$ `git checkout -b modernize-python2-code`
$ `futurize --stage1 -w **/*.py`  # done in zsh for ** globbing
$ `git commit --all -m "Modernize Python 2 code to get ready for Python 3"`
$ `git push --set-upstream origin modernize-python2-code`
> Modernize Python 2 code to get ready for Python 3

- .travis.yml
@jmcanterafonseca For your review, this should close #147
> Turn on zero tolerance for PEP8 violations

- Weather/WeatherAlarm/meteoalarm.py
> Simplify meteoalarm.py w/ ternary if & dict get()

- Environment/AirQualityObserved/harvest/ngsi_helper.py
dict.get() with empty list as default arguement plus list comprehension.
> Simplify ngsi_helper.py

- Transportation/Bike/BikeHireDockingStation/example.json
- Transportation/Bike/BikeHireDockingStation/schema.json
> Fix BikeHireDockingStation example.json

- README.md
details on the data model folder structure have been added to the readme.
> Extend how to contribute

- Weather/WeatherForecast/harvest/aemet.py
Also simplify with "or", enumerate(), tuple unpacking, ternary if, etc.
> Simplify aemet.py: function lookup, dict building

- common-schema.json
fix missing } in common-schema.json
> fix missing } in common-schema.json

- .travis.yml
Fixes #173
@chicco785 Perhaps you can give me some hints on
* https://travis-ci.org/Fiware/dataModels/jobs/290872645#L470
> Add jshint linting to .travis.yml

- Weather/WeatherForecast/harvest/spain_weather_forecast_harvest.py
* ternary if
* str.format() for zero filling numeric string
* suppress flake8 F841 unused variable warning
> Remove unused imports, simplify w/ +=, dict.get()

- Device/Device/example.json
- Device/Device/schema.json
- Device/DeviceModel/example.json
- Device/DeviceModel/schema.json
- Device/device-schema.json
Schemas and Examples for:
* Device
* DeviceModel
> Device datamodel json schema

- Environment/AirQualityObserved/README.md
removed measurand from the readme example #195
> removed measurand from the readme example

- Alert/doc/spec.md
fix alert docs indentation for readthedocs
> fix alert docs indentation for readthedocs

- Device/Device/doc/spec.md
- Device/Device/example.json
> Encoded value attribute in the JSON Example

- User/Activity/README.md
- User/Activity/doc/spec.md
- User/Activity/example.json
- User/Activity/schema.json
- User/README.md
- User/UserContext/README.md
- User/UserContext/doc/spec.md
- User/UserContext/example.json
- User/UserContext/schema.json
This commit contains a number of data models related to the modelling
of User Context.
The following entity types are supported:
- `UserContext` - An Entity that represents the context of a given user.
- `Activity` - An Entity that represents an activity performed by a
given user.
> New model aimed at modelling user related context.

- Parking/ParkingSpot/schema.json
- ParksAndGardens/FlowerBed/schema.json
- ParksAndGardens/Garden/schema.json
- ParksAndGardens/GreenspaceRecord/schema.json
- Transportation/Road/schema.json
- Transportation/RoadSegment/schema.json
- Transportation/Vehicle/Vehicle/schema.json
- Transportation/Vehicle/VehicleModel/schema.json
Providing schema.json files for Road, RoadSegment, VehicleModel, Vehicle, Flowerbed, Garden, GreenspaceRecord, ParkingSpot entities
> Xapix schema contributions

- Transportation/Vehicle/Vehicle/schema.json
Analyzing the excellent contribution of @ 10aboskin, he may have forgotten this detail. Or not...
> added type string in schema.json of Vehicle in serviceProvided attribute

- Transportation/Bike/BikeHireDockingStation/doc/spec.md
- Transportation/Bike/BikeHireDockingStation/schema.json
This pull request fix issue #223
> BikeHireDockingStation Spec: Mark location as mandatory if address is not provided

- Weather/WeatherForecast/harvest/portugal_weather_forecast_harvest.py
- Weather/WeatherForecast/harvest/spain_weather_forecast_harvest.py
- Weather/WeatherObserved/harvest/portugal_weather_observed_harvest.py
- Weather/WeatherObserved/harvest/spain_weather_observed_harvest.py
> Remove TEF as provider and substitute it by FIWARE

- Weather/WeatherObserved/harvest/portugal_weather_observed_harvest.py
> Portugal command line parameters - Only latest observations

- Environment/AeroAllergenObserved/README.md
- Environment/AeroAllergenObserved/doc/spec.md
- Environment/AeroAllergenObserved/example.json
- Environment/AeroAllergenObserved/schema.json
- Environment/doc/introduction.md
- mkdocs.yml
Provide a data model for Aero Allergen Observed as discussed in #221
> Aero Allergen Observed data model draft

- UrbanMobility/Route/doc/spec.md
- UrbanMobility/Route/example.json
- UrbanMobility/Route/schema.json
- UrbanMobility/Trip/doc/spec.md
- UrbanMobility/Trip/example.json
- UrbanMobility/Trip/schema.json
> GTFS - Part II

- mkdocs.yml
- specs/KeyPerformanceIndicator/doc/spec.md
- specs/Parking/OffStreetParking/doc/spec.md
- specs/Parking/OnStreetParking/doc/spec.md
- specs/Parking/ParkingSpot/doc/spec.md
- specs/PointOfInteraction/SmartSpot/doc/spec.md
- specs/PointOfInterest/Beach/doc/spec.md
- specs/StreetLighting/StreetlightControlCabinet/doc/spec.md
- specs/StreetLighting/StreetlightModel/doc/spec.md
- specs/UrbanMobility/AccessPoint/doc/spec.md
- specs/UrbanMobility/Agency/doc/spec.md
- specs/UrbanMobility/CalendarDateRule/doc/spec.md
- specs/UrbanMobility/CalendarRule/doc/spec.md
- specs/UrbanMobility/Frequency/doc/spec.md
- specs/UrbanMobility/README.md
- specs/UrbanMobility/Route/doc/spec.md
- specs/UrbanMobility/Service/doc/spec.md
- specs/UrbanMobility/Station/doc/spec.md
- specs/UrbanMobility/Stop/doc/spec.md
- specs/UrbanMobility/StopTime/doc/spec.md
- specs/UrbanMobility/TransferRule/doc/spec.md
- specs/UrbanMobility/Trip/doc/spec.md
- specs/WasteManagement/WasteContainer/doc/spec.md
- specs/Weather/WeatherObserved/doc/spec.md
> fix: markdown lists, mkdocs config

- specs/Environment/AirQualityObserved/harvest/barcelona_airquality_harvest.py
- specs/Environment/AirQualityObserved/harvest/madrid_air_quality_harvest.py
modified the air quality harvester to accept parameter -  
example : python madrid_air_quality_harvest.py 28079059 --service fiwareExample --service-path / --endpoint http://localhost:1026 --latest
@caa06d9c 
@jmcanterafonseca
> modified madrid_air_air_quality to accept command line parameters

- specs/Transportation/doc/introduction.md
> update documentation links for Transportation

- README.md
- mkdocs.yml
- specs/guidelines.md
- specs/howto.md
* first draft of some content in relation to #301 
@jmcanterafonseca it's just a starting point to gather feedbacks of what should go in here before going too much ahead. i suspect that probably some content may be more appropriate here than in guidelines for development.
> guide on data model adoption (#301)

- specs/Environment/AirQualityObserved/doc/spec.md
> first modification for the specs document examples format

- specs/Environment/AeroAllergenObserved/doc/spec.md
- specs/Environment/AirQualityObserved/doc/spec.md
- specs/Parking/OffStreetParking/doc/spec.md
- specs/Parking/OnStreetParking/doc/spec.md
- specs/Parking/ParkingGroup/doc/spec.md
- specs/Parking/ParkingSpot/doc/spec.md
- specs/PointOfInterest/AirQualityStation/README.md
- specs/PointOfInterest/Beach/doc/spec.md
- specs/PointOfInterest/Museum/doc/spec.md
- specs/Transportation/EVChargingStation/doc/spec.md
- specs/Transportation/RoadSegment/doc/spec.md
- specs/Transportation/Vehicle/Vehicle/doc/spec.md
- specs/User/Activity/doc/spec.md
- specs/Weather/WeatherForecast/README.md
- specs/Weather/WeatherObserved/doc/spec.md
- specs/howto.md
- validator/.textlintrc
- validator/package-lock.json
- validator/package.json
* Added filters to avoid false positives
* Updated spelling mistakes and dead URLs.
> Updating text linting rules and scope

- specs/Parking/OffStreetParking/doc/spec.md
- specs/Parking/OnStreetParking/doc/spec.md
- specs/Parking/ParkingAccess/doc/spec.md
- specs/Parking/ParkingGroup/doc/spec.md
- specs/Parking/ParkingSpot/doc/spec.md
corrected the files in the Parking folder in the DataModel repo. 
@jmcanterafonseca
> Parking Folder Specs modifications for the normalized examples

- specs/StreetLighting/Streetlight/doc/spec.md
- specs/StreetLighting/Streetlight/schema.json
- specs/StreetLighting/StreetlightControlCabinet/doc/spec.md
- specs/StreetLighting/StreetlightControlCabinet/schema.json
- specs/StreetLighting/StreetlightGroup/doc/spec.md
- specs/StreetLighting/StreetlightGroup/example.json
- specs/StreetLighting/StreetlightGroup/schema.json
- specs/StreetLighting/StreetlightModel/example.json
- specs/StreetLighting/StreetlightModel/schema.json
- validator/libs/schema.js
This PR fixes some problems in the StreetLightning specifications and provides initial JSON schemas for the `StreetlightGroup` and `StreetlightModel` data models.
> Fix some StreetLighting doc details

- specs/Transportation/Vehicle/Vehicle/doc/spec.md
In this pull request I modified the vehicle data model according to the issue here https://github.com/Fiware/dataModels/issues/326 
@jmcanterafonseca
> modified datamodel bullets for issue #326

- specs/PointOfInterest/PointOfInterest/doc/spec.md
@emastrosimone could you r? please
> Extra Categories for POI

- specs/Transportation/Bike/BikeHireDockingStation/doc/spec.md
- specs/Transportation/CrowdFlowObserved/doc/spec.md
- specs/Transportation/EVChargingStation/doc/spec.md
- specs/Transportation/Road/doc/spec.md
- specs/Transportation/RoadSegment/doc/spec.md
- specs/Transportation/TrafficFlowObserved/doc/spec.md
- specs/Transportation/Vehicle/Vehicle/doc/spec.md
- specs/Transportation/Vehicle/VehicleModel/doc/spec.md
> Modified Examples in the Transportation Folder

- specs/Weather/WeatherForecast/doc/spec.md
- specs/Weather/WeatherObserved/doc/spec.md
> Modified Examples in the Weather Folder

- specs/UrbanMobility/AccessPoint/doc/spec.md
- specs/UrbanMobility/Agency/doc/spec.md
- specs/UrbanMobility/ArrivalEstimation/doc/spec.md
- specs/UrbanMobility/CalendarDateRule/doc/spec.md
- specs/UrbanMobility/CalendarRule/doc/spec.md
- specs/UrbanMobility/Frequency/doc/spec.md
- specs/UrbanMobility/Route/doc/spec.md
- specs/UrbanMobility/Service/doc/spec.md
- specs/UrbanMobility/Station/doc/spec.md
- specs/UrbanMobility/Stop/doc/spec.md
- specs/UrbanMobility/StopTime/doc/spec.md
- specs/UrbanMobility/TransferRule/doc/spec.md
- specs/UrbanMobility/Trip/doc/spec.md
> Modified Examples in the UrbanMobility Folder

- specs/Environment/WaterQualityObserved/doc/spec.md
- specs/Environment/WaterQualityObserved/example-normalized.json
@jmcanterafonseca - This is a first try of adding the normalised examples.
> added a normalised example

- specs/Environment/AeroAllergenObserved/doc/spec.md
- specs/Environment/AeroAllergenObserved/example-normalized.json
> added the normalized example to the Environment folder

- specs/PointOfInterest/Beach/doc/spec.md
- specs/PointOfInterest/Beach/example-normalized.json
- specs/PointOfInterest/Museum/doc/spec.md
- specs/PointOfInterest/Museum/example-normalized.json
- specs/PointOfInterest/PointOfInterest/doc/spec.md
> added the normalized example to the PointOfIntrest folder

- specs/User/Activity/doc/spec.md
- specs/User/Activity/example-normalized.json
- specs/User/UserContext/doc/spec.md
- specs/User/UserContext/example-normalized.json
> added the normalized example to the User folder

- specs/WasteManagement/WasteContainer/doc/spec.md
- specs/WasteManagement/WasteContainer/example-normalized.json
- specs/WasteManagement/WasteContainerIsle/doc/spec.md
- specs/WasteManagement/WasteContainerIsle/example-normalized.json
- specs/WasteManagement/WasteContainerModel/doc/spec.md
- specs/WasteManagement/WasteContainerModel/example-normalized.json
> added the normalized example to the WassteManagement folder

- specs/Alert/doc/spec.md
> fixed the normalized example to the Alert folder

- specs/Building/Building/doc/spec.md
- specs/Building/Building/example-normalized.json
- specs/Building/BuildingOperation/doc/spec.md
- specs/Building/BuildingOperation/example-normalized.json
> added the normalized example to the building folder

- specs/Device/Device/doc/spec.md
- specs/Device/Device/example-normalized.json
- specs/Device/DeviceModel/doc/spec.md
- specs/Device/DeviceModel/example-normalized.json
> added the normalized example to the Device folder

- specs/PointOfInteraction/SmartPointOfInteraction/doc/spec.md
- specs/PointOfInteraction/SmartPointOfInteraction/example-normalized.json
- specs/PointOfInteraction/SmartSpot/doc/spec.md
- specs/PointOfInteraction/SmartSpot/example-normalized.json
> added the normalized example to the PointOfInteraction folder

- specs/IssueTracking/Open311_ServiceRequest/doc/spec.md
- specs/IssueTracking/Open311_ServiceRequest/example-normalized.json
- specs/IssueTracking/Open311_ServiceRequest/example.json
- specs/IssueTracking/Open311_ServiceType/doc/spec.md
- specs/IssueTracking/Open311_ServiceType/example-normalized.json
- specs/IssueTracking/Open311_ServiceType/example.json
> added the normalized example to the IssueTracking folder

- specs/KeyPerformanceIndicator/doc/spec.md
- specs/KeyPerformanceIndicator/example-normalized.json
- specs/KeyPerformanceIndicator/example.json
> added the normalized example to the KeyPerformanceIndicator folder

- specs/Transportation/Road/doc/spec.md
- specs/Transportation/Road/example-normalized.json
- specs/Transportation/Road/example.json
- specs/Transportation/RoadSegment/doc/spec.md
- specs/Transportation/RoadSegment/example-normalized.json
- specs/Transportation/RoadSegment/example.json
> added the normalized example to the Transportation folder

- .travis.yml
Since #320 has been applied, it is now safe to re-add the travis change proposed to check links - 086d8fb95 - this should properly close the #318
You can see the current result is Green: https://travis-ci.org/jason-fox/dataModels/jobs/481271246
> Add textlint to travis. Fix #318

- specs/Building/README.md
- specs/Environment/AeroAllergenObserved/doc/spec.md
> fix travis build

- specs/AgriFood/AgriParcel/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcel/example-normalized.json
- specs/AgriFood/AgriParcel/example.json
- specs/AgriFood/AgriParcel/schema.json
> Add ownedBy attribute to AgriParcel data model

- specs/AgriFood/AgriGreenhouse/example-normalized-ld.jsonld
- specs/AgriFood/AgriGreenhouse/example-normalized.json
- specs/AgriFood/AgriGreenhouse/example.json
- specs/AgriFood/AgriGreenhouse/schema.json
> Add ownedBy attribute to AgriGreenHouse data model

- specs/AgriFood/AgriPest/example-normalized-ld.jsonld
- specs/AgriFood/AgriPest/example-normalized.json
- specs/AgriFood/AgriPest/example.json
- specs/AgriFood/AgriPest/schema.json
> Add AgroVocConcept attribute to AgriPest data model

- specs/AgriFood/AgriProductType/example-normalized-ld.jsonld
- specs/AgriFood/AgriProductType/example-normalized.json
- specs/AgriFood/AgriProductType/example.json
- specs/AgriFood/AgriProductType/schema.json
> Add AgroVocConcept attribute to AgriProductType data model

- specs/AgriFood/AgriFarm/example-normalized-ld.jsonld
- specs/AgriFood/AgriFarm/example-normalized.json
- specs/AgriFood/AgriFarm/example.json
- specs/AgriFood/AgriFarm/schema.json
> Add AgriFarm data model

- specs/AgriFood/AgriCrop/example-normalized-ld.jsonld
- specs/AgriFood/AgriCrop/example-normalized.json
- specs/AgriFood/AgriCrop/example.json
- specs/AgriFood/AgriCrop/schema.json
> Add seeAlso attribute to AgriCrop data model

- specs/AgriFood/AgriParcel/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcel/example-normalized.json
- specs/AgriFood/AgriParcel/example.json
- specs/AgriFood/AgriParcel/schema.json
> Add belongsTo attribute to AgriParcel data model

- specs/AgriFood/AgriApp/example-normalized-ld.jsonld
- specs/AgriFood/AgriApp/example-normalized.json
- specs/AgriFood/AgriApp/example.json
- specs/AgriFood/AgriApp/schema.json
> Add a new AgriApp data model

- common-schema.json
> Add seeAlso attribute definition to common-schema.json

- specs/AgriFood/AgriGreenhouse/example-normalized-ld.jsonld
- specs/AgriFood/AgriGreenhouse/example-normalized.json
- specs/AgriFood/AgriGreenhouse/example.json
- specs/AgriFood/AgriGreenhouse/schema.json
> Add seeAlso attribute to AgriGreenhouse data model

- specs/AgriFood/AgriParcel/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcel/example-normalized.json
- specs/AgriFood/AgriParcel/example.json
- specs/AgriFood/AgriParcel/schema.json
> Add seeAlso attribute to AgriParcel data model

- specs/AgriFood/AgriParcelRecord/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelRecord/example-normalized.json
- specs/AgriFood/AgriParcelRecord/example.json
- specs/AgriFood/AgriParcelRecord/schema.json
> Add see also attribute to AgriParcelRecord data model

- specs/AgriFood/AgriCrop/schema.json
>  Remove seeAlso attribute from AgriCrop schema

- specs/AgriFood/AgriFarm/example-normalized-ld.jsonld
- specs/AgriFood/AgriFarm/example-normalized.json
- specs/AgriFood/AgriFarm/example.json
> Include seeAlso attribute to AgriFarm examples

- specs/AgriFood/AgriPest/example-normalized-ld.jsonld
- specs/AgriFood/AgriPest/example-normalized.json
- specs/AgriFood/AgriPest/example.json
- specs/AgriFood/AgriPest/schema.json
> Add seeAlso attribute to AgriPest data model

- specs/AgriFood/AgriParcelOperation/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelOperation/example-normalized.json
- specs/AgriFood/AgriParcelOperation/example.json
- specs/AgriFood/AgriParcelOperation/schema.json
> Add seeAlso attribute to AgriParcelOperation data model

- specs/AgriFood/AgriGreenhouse/example-normalized-ld.jsonld
- specs/AgriFood/AgriGreenhouse/example-normalized.json
- specs/AgriFood/AgriGreenhouse/example.json
- specs/AgriFood/AgriGreenhouse/schema.json
> Add belongsTo attribute to AgriGreenHouse data model

- specs/Parking/OffStreetParking/doc/spec.md
- specs/Parking/OnStreetParking/doc/spec.md
#447 
An order to improve the reading of attributes in the spec.md documentation
Thank you
> #447 reorder attributtes

- .travis.yml
- specs/AgriFood/AgriApp/schema.json
- specs/AgriFood/AgriCrop/schema.json
- specs/AgriFood/AgriFarm/schema.json
- specs/AgriFood/AgriGreenhouse/schema.json
- specs/AgriFood/AgriParcel/schema.json
- specs/AgriFood/AgriParcelOperation/schema.json
- specs/AgriFood/AgriParcelRecord/schema.json
- specs/AgriFood/AgriPest/schema.json
- specs/AgriFood/AgriProductType/schema.json
- specs/AgriFood/agrifood-schema.json
> Add a common schema for AgriFood entities

- specs/AgriFood/AgriCrop/example-normalized-ld.jsonld
- specs/AgriFood/AgriCrop/example-normalized.json
- specs/AgriFood/AgriCrop/example.json
- specs/AgriFood/AgriCrop/schema.json
> Add relatedSource attribute to AgriCrop data model

- specs/AgriFood/AgriFarm/example-normalized-ld.jsonld
- specs/AgriFood/AgriFarm/example-normalized.json
- specs/AgriFood/AgriFarm/example.json
> Add relatedSource attribute to AgriFarm examples

- specs/AgriFood/AgriGreenhouse/example-normalized-ld.jsonld
- specs/AgriFood/AgriGreenhouse/example-normalized.json
- specs/AgriFood/AgriGreenhouse/example.json
> Add relatedSource attribute to AgriGreenhouse examples

- specs/AgriFood/AgriParcel/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcel/example-normalized.json
- specs/AgriFood/AgriParcel/example.json
> Add relatedSource attribute to AgriParcel examples

- specs/AgriFood/AgriParcelOperation/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelOperation/example-normalized.json
- specs/AgriFood/AgriParcelOperation/example.json
> Add relatedSource attribute to AgriParcelOperation examples

- specs/AgriFood/AgriParcelRecord/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelRecord/example-normalized.json
- specs/AgriFood/AgriParcelRecord/example.json
> Add relatedSource attribute to AgriParcelRecord examples

- specs/AgriFood/AgriPest/example-normalized-ld.jsonld
- specs/AgriFood/AgriPest/example-normalized.json
- specs/AgriFood/AgriPest/example.json
> Add relatedSource attribute to AgriPest examples

- specs/AgriFood/AgriProductType/example-normalized-ld.jsonld
- specs/AgriFood/AgriProductType/example-normalized.json
- specs/AgriFood/AgriProductType/example.json
> Add relatedSource attribute to AgriProductType examples

- specs/IssueTracking/Open311_ServiceRequest/doc/spec.md
- specs/IssueTracking/Open311_ServiceRequest/example-normalized.json
- specs/IssueTracking/Open311_ServiceRequest/example.json
- specs/IssueTracking/Open311_ServiceRequest/schema.json
- specs/IssueTracking/Open311_ServiceType/doc/spec.md
- specs/IssueTracking/Open311_ServiceType/example-normalized.json
- specs/IssueTracking/Open311_ServiceType/example.json
- specs/IssueTracking/Open311_ServiceType/schema.json
> Fix open311 type name (Fixes #462)

- specs/AgriFood/AgriParcelOperation/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelOperation/example-normalized.json
- specs/AgriFood/AgriParcelOperation/example.json
- specs/AgriFood/AgriParcelOperation/schema.json
> Add workOrder, workRecord and irrigationRecord to AgriParcelOperation

- specs/Device/DeviceModel/doc/spec.md
- specs/Device/device-schema.json
> Add new category types to Device data models

- specs/PointOfInterest/WeatherStation/harvesters/spain/spain_weather_stations.py
- specs/Weather/WeatherForecast/harvesters/portugal/portugal_weather_forecast.py
- specs/Weather/WeatherForecast/harvesters/spain/spain_weather_forecast.py
- specs/Weather/WeatherObserved/harvesters/portugal/portugal_weather_observed.py
- specs/Weather/WeatherObserved/harvesters/spain/spain_weather_observed.py
'Streams' instance and postman recipes were updated too.
Documentation will be changed together with other GSMA changes.
Step 1 from :https://github.com/FIWARE/dataModels/issues/476
> The header FIWARE-ServicePath was removed from harvesters

- README.md
- specs/Building/Building/doc/spec.md
- specs/Building/BuildingOperation/doc/spec.md
- specs/Building/README.md
- specs/Device/Device/doc/spec.md
- specs/Environment/AeroAllergenObserved/doc/spec.md
- specs/Environment/AirQualityObserved/README.md
- specs/Environment/AirQualityObserved/doc/spec.md
- specs/PointOfInterest/README.md
- specs/PointOfInterest/WeatherStation/README.md
- specs/Transportation/Road/doc/spec.md
- specs/Transportation/RoadSegment/doc/spec.md
- specs/Weather/WeatherAlert/README.md
- specs/Weather/WeatherForecast/README.md
- specs/Weather/WeatherForecast/doc/spec.md
- specs/Weather/WeatherObserved/README.md
- specs/Weather/WeatherObserved/doc/spec.md
- specs/gsma.md
- validator/.textlintrc
Together with https://github.com/FIWARE/dataModels/issues/477 (step 2) and https://github.com/FIWARE/dataModels/issues/476 (only those types that exist in streams server)
> fix broken links

- specs/PointOfInterest/WeatherStation/harvesters/spain/spain_weather_stations.py
- specs/Weather/WeatherForecast/harvesters/portugal/portugal_weather_forecast.py
- specs/Weather/WeatherForecast/harvesters/spain/spain_weather_forecast.py
- specs/Weather/WeatherObserved/harvesters/portugal/portugal_weather_observed.py
- specs/Weather/WeatherObserved/harvesters/spain/spain_weather_observed.py
It fixes ID only for 5 harvesters, that were refactored early.
> fix #482, id changed

- specs/AgriFood/Animal/doc/spec.md
- specs/AgriFood/Animal/example-normalized-ld.jsonld
- specs/AgriFood/Animal/example-normalized.json
- specs/AgriFood/Animal/example.json
- specs/AgriFood/Animal/schema.json
> Add relatedSource attribute to Animal data model

- specs/AgriFood/AgriApp/example-normalized-ld.jsonld
- specs/AgriFood/AgriCrop/example-normalized-ld.jsonld
- specs/AgriFood/AgriFarm/example-normalized-ld.jsonld
- specs/AgriFood/AgriGreenhouse/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcel/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelOperation/example-normalized-ld.jsonld
- specs/AgriFood/AgriParcelRecord/example-normalized-ld.jsonld
- specs/AgriFood/AgriPest/example-normalized-ld.jsonld
- specs/AgriFood/AgriProductType/example-normalized-ld.jsonld
> Update context of Agri models LD examples

- specs/Building/Building/README.md
- specs/Building/Building/doc/spec.md
- specs/Building/Building/example-normalized-ld.jsonld
- specs/Building/Building/example-normalized.json
- specs/Building/Building/example.json
- specs/Building/Building/schema.json
- specs/Building/BuildingOperation/doc/spec.md
- specs/Building/README.md
*  Update schema - replace object array with string array.
*  Update `README` and examples
> Fix #504 - Amend Building.openingHours to align with schema.org

- specs/PointOfInterest/WeatherStation/harvesters/spain/Dockerfile
- specs/PointOfInterest/WeatherStation/harvesters/spain/README.md
- specs/PointOfInterest/WeatherStation/harvesters/spain/requirements.txt
- specs/PointOfInterest/WeatherStation/harvesters/spain/spain_weather_stations.py
- specs/Weather/WeatherForecast/harvesters/portugal/Dockerfile
- specs/Weather/WeatherForecast/harvesters/portugal/portugal_weather_forecast.py
- specs/Weather/WeatherForecast/harvesters/portugal/requirements.txt
- specs/Weather/WeatherForecast/harvesters/spain/Dockerfile
- specs/Weather/WeatherForecast/harvesters/spain/README.md
- specs/Weather/WeatherForecast/harvesters/spain/requirements.txt
- specs/Weather/WeatherForecast/harvesters/spain/spain_weather_forecast.py
- specs/Weather/WeatherObserved/harvesters/portugal/Dockerfile
- specs/Weather/WeatherObserved/harvesters/portugal/portugal_weather_observed.py
- specs/Weather/WeatherObserved/harvesters/portugal/requirements.txt
- specs/Weather/WeatherObserved/harvesters/spain/Dockerfile
- specs/Weather/WeatherObserved/harvesters/spain/requirements.txt
- specs/Weather/WeatherObserved/harvesters/spain/spain_weather_observed.py
- uvloop added (performance)
- weather_type for Portugal weather forecast extended with additional values
- timeout implemented properly
- docker images fixed
> small changes in harvesters

- README.md
- specs/Weather/weather-schema.json
- tools/ldcontext_generator.json
The main fix is for "visibility, "windDirection", I suppose, should be changed to a number too, an integer is not in NGSI
> fix #282 - adding number as available type

- tools/ldcontext_generator.py
also, URL of spec changed to readthedocs.
> type added to term

- specs/AgriFood/AgriApp/schema.json
- specs/AgriFood/AgriCrop/schema.json
- specs/AgriFood/AgriFarm/schema.json
- specs/AgriFood/AgriGreenhouse/schema.json
- specs/AgriFood/AgriParcel/schema.json
- specs/AgriFood/AgriParcelOperation/schema.json
- specs/AgriFood/AgriParcelRecord/schema.json
- specs/AgriFood/AgriPest/schema.json
- specs/AgriFood/AgriProductType/schema.json
- specs/AgriFood/Animal/schema.json
- specs/AgriFood/agrifood-schema.json
> Use EntityIdentifierType en Agrifood models

- specs/AgriFood/AgriParcel/example-normalized.json
- specs/AgriFood/AgriParcelRecord/example-normalized.json
> Add DateTime type to timestamps in metadata

- specs/AgriFood/AgriProductType/example-normalized-ld.jsonld
- specs/AgriFood/AgriProductType/example-normalized.json
- specs/AgriFood/AgriProductType/example.json
- specs/AgriFood/AgriProductType/schema.json
- specs/guidelines.md
> Add category property to AgriProductType data model

- mkdocs.yml
- specs/AgriFood/README.md
> Update AgriFood README and mkdocs

- specs/KeyPerformanceIndicator/doc/spec.md
Correction of the case-sensitive url for the Organization schema.
> Fix broken link
