FIWARE/data-models

- WasteManagement/WasteContainer/doc/spec.md
- WasteManagement/WasteContainerIsle/doc/spec.md
Dear team,
I suggest the following change on the basis of the recently released RFC 7946 for GeoJSON format by the IETF (2016-08-10): https://datatracker.ietf.org/wg/geojson/documents/
In the coming months GeoJSON format probably already become standard, so there will be new changes. I think it's better to put the link to IETF datatracker (instead a direct link to last documents) where is the status of the format and the link to the last document.
I did not change any more that line 15 from both files but Git have been tracked as changes (and there are no more changes at all) the change of tabs for spaces (or something like that).
Cayetano Benavent,
GEOGRAPHICA
> updated GeoJSON Normative References for WasteManagement

- IssueTracking/Open311_ServiceType/doc/spec.md
- KeyPerformanceIndicator/doc/spec.md
- Parking/ParkingSpot/doc/spec.md
- StreetLighting/Streetlight/doc/spec.md
- StreetLighting/StreetlightControlCabinet/doc/spec.md
- StreetLighting/StreetlightGroup/doc/spec.md
- WasteManagement/WasteContainer/doc/spec.md
- WaterQuality/WaterQualityObserved/doc/spec.md
- guidelines.md
please note that at entity level  `dateUpdated` is now `dateModified` as per NGSIv2 that's why a small number of renames are to `dateModified`
> `dateUpdated`  --> `timestamp`

- PointOfInterest/import_pois_tourspain.py
Seems that current versions of the Orion Context Broker is not able to handle EOL characters inside attribute values.
> Remove eol characters from descriptions

- .travis.yml
These tests currently pass so let's use Travis CI to ensure that future pull requests do not backslide.  The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.
> Use Travis CI and flake8 to ensure the code quality of future pull requests

- WasteManagement/WasteContainerIsle/example.json
- WasteManagement/WasteContainerIsle/schema.json
- WasteManagement/WasteContainerModel/example.json
- WasteManagement/WasteContainerModel/schema.json
As mentioned in #151 I did work out some of the missing json example and schemas for the existing models. These are the one for WasteContainerIsle and WasteContainerModel.
> Waste management missing json

- PointOfInteraction/SmartPointOfInteraction/schema.json
- PointOfInteraction/SmartSpot/schema.json
afaik, url is not a valid format in json schema, replaced with uri
which is a super set of url, better would be probably to use a pattern.
feedbacks?
> Fix url string format PoinOfInteraction

- Environment/AirQualityObserved/harvest/barcelona_airquality_harvest.py
- Environment/AirQualityObserved/harvest/madrid_air_quality_harvest.py
- Environment/AirQualityObserved/harvest/malaga_airqualityobserved_import.py
- Environment/AirQualityObserved/harvest/santander_federation.py
- PointOfInterest/import_pois_tourspain.py
- Transportation/Bike/BikeHireDockingStation/harvest/bicycle_hire_station_barcelona_harvest.py
- Weather/WeatherForecast/harvest/portugal_weather_forecast_harvest.py
- Weather/WeatherForecast/harvest/spain_weather_forecast_harvest.py
- Weather/WeatherObserved/harvest/portugal_weather_observed_harvest.py
- Weather/WeatherObserved/harvest/spain_weather_observed_harvest.py
Fixes #169 Remove `from __future__ import with_statement` which has not been needed post Python 2.5.
> Remove anachronistic import with_statement (not so scary version)

- Device/Device/doc/spec.md
- common-schema.json
- datamodel_template.md
Checking the original GSMA Device Data Model we found out that the owner attribute is missing. We believe this is an relevant attribute in several scenarios.
* Added owner property as array of uris to common-schema.json to match GSMA Device Data Model
* Added owner property to GSMA Device Data Model spec
> Add owner to gsma common schema

- .travis.yml
This consolidates all of the JavaScript testing into the node_js section instead of running jshint twice in the Python2 and in the Python3 sections.
> Try moving jshint work into the node_js section

- Transportation/TrafficFlowObserved/doc/spec.md
Hello, trying to send the example of the TrafficFlowObserved data model to the Context Broker, the Rest client was throwing me an error. in this commit the error is solved.
Error:
`` {
"error": "ParseError",
"description": "Errors found in incoming JSON buffer"
} ``
Cause: The comma in the attribute is missing:  `"capacity": 0.76`.
Solution: The comma is added to the end of the attribute.
Greetings.
>  Error sending the TrafficFlowObserved data model.

- Device/Device/doc/spec.md
- Device/DeviceModel/doc/spec.md
* Missing `DateTime` in Device spec
* Misspelling in the Device example
* Incorrect date format in the Device example (it was Date while the
specs reports DateTime)
* Removed duplicated `pressure`in DeviceModel
> minor fixes to Device and DeviceModel documentation

- .travis.yml
without a version provided, travis-ci uses nodejs 0.10
> added node_js version to ci tests

- WasteManagement/WasteContainer/doc/spec.md
- WasteManagement/WasteContainer/example.json
changed in the examples `dateNextActuation` to `nextActuationDeadline`
to comply with spec
fix issue #190
> DateNextActuation fix

- Transportation/Bike/BikeHireDockingStation/doc/spec.md
- Transportation/Bike/BikeHireDockingStation/schema.json
`BikeHireDockingStation` Spec allows to use the `full` and `almostFull` statuses, but not the opposites: `empty` and `almostEmpty`. From the point of view of a docking station manager, those status are useful as they indicates that some maintenance task has to be done (e.g. moving some bikes to the empty docking stations so clients can use them). We know that the spec does not forbid the use of those status, but we think they will be used with the same frequency as `full` and `almostFull`, so it is better to have them documented.
> BikeHireDockingStation: add empty and almostEmpty status

- Device/DeviceModel/doc/spec.md
- Device/DeviceModel/schema.json
- Device/device-schema.json
- Environment/AirQualityObserved/harvest/madrid_air_quality.py
- Environment/AirQualityObserved/harvest/madrid_air_quality_harvest.py
- Weather/WeatherObserved/doc/spec.md
- Weather/WeatherObserved/example.json
- Weather/WeatherObserved/schema.json
This PR fixes issue #234, that is, it replaces the `barometricPressure` attribute on the `WeatherObserved` model with the `atmosphericPressure` attribute, that is the attribute documented by GSMA. This PR also replaces other occurrences in the `DeviceModel` spec and in the `AirQualityObserved` example harvesters.
> Use Atmospheric Pressure instead of Barometric Pressure

- Transportation/Vehicle/Vehicle/doc/spec.md
- Transportation/Vehicle/Vehicle/schema.json
This PR adds a `fleetVehicleId` attribute to the `Vehicle` data model both in the spec documentation and in the schema.
> Add a fleetVehicleId attribute to the Vehicle model. Fix #231

- specs/StreetLighting/Streetlight/doc/spec.md
- specs/StreetLighting/Streetlight/example.json
- specs/StreetLighting/Streetlight/schema.json
- specs/StreetLighting/StreetlightControlCabinet/doc/spec.md
- specs/StreetLighting/StreetlightControlCabinet/example.json
- specs/StreetLighting/StreetlightControlCabinet/schema.json
This PR adds a `refDevice` attribute to the `Streetlight` and to the `StreetlightControlCabinet` data models. This attribute works in the same way in the [`WasterContainer` data model](https://github.com/Fiware/dataModels/blob/master/specs/WasteManagement/WasteContainer/doc/spec.md).
As there is not schema file for those datamodels, this PR also add an initial version of the schema for those datamodels.
> Add refDevice attribute into the Streetlight and to the StreetlightControlCabinet models

- specs/StreetLighting/doc/introduction.md
Link of StreetlightGroup is changen to "../StreetlightGroup/doc/spec.md". Because he was going  to "../Streetlight/doc/spec.md".
In the "https://fiware-datamodels.readthedocs.io/en/latest/StreetLighting/doc/introduction/index.html" I saw this issue
> Update link StreetlightGroup

- mkdocs.yml
The ThreePhaseAcMeasurement (pull request #388) was not included to the data models web page since it was missing from the mkdocs.yml file.
> Update mkdocs.yml to contain the ThreePhaseAcMeasurement data model

- specs/UrbanMobility/GtfsStop/doc/spec.md
- specs/UrbanMobility/GtfsStop/schema.json
Make 'operatedBy' Optional, since its not mentioned in google's documentation for Stops in GTFS feed
> Make 'operatedBy' Optional (Partial fix for #463)

- specs/UrbanMobility/GtfsStop/doc/spec.md
- specs/UrbanMobility/GtfsStop/example.json
- specs/UrbanMobility/GtfsStop/schema.json
Make 'operatedBy' an array of references, to allow several agencies to be referred as operating in the Stop.
I created separate PR, to ease cherrypicking in case it needs further discussion.
> Make 'operatedBy' an array of references (Partial fix for #463)

- tools/ldcontext_mappings.json
`aggregateRating` - only used in `specs/Parking/OffStreetParking/schema.json` - states https://schema.org/aggregateRating is normative. This PR adds a mapping to ensure this is the case with the linked-data specification.
> Add aggregateRating mapping
